# Generated by Django 4.2.2 on 2023-06-28 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_booking_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AddField(
            model_name='booking',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date_modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
