# Generated by Django 4.2.2 on 2023-06-28 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_booking_options_booking_date_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +380xxxxxxxxx, 0xxxxxxxxx', regex='^(+38)?0\\d{9}$')])),
                ('date_time', models.DateTimeField()),
                ('people', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('is_processed', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
    ]
