# Generated by Django 4.2.2 on 2023-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_userbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='date_time',
            field=models.CharField(max_length=20),
        ),
    ]
