# Generated by Django 4.2.2 on 2023-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_userbooking_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBooking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date_in',)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
